# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: dotnet restore eShopOnWeb.sln
  displayName: NuGet Restore

- task: component-detection-github-submission-task@0
  inputs:
    githubRepository: 'testing-felickz/eShopOnWeb'
    token: '$(GH_TOKEN)'
    filePath: '$(Build.SourcesDirectory)'
